### ISSUE TITLE
NPE if URL is not given

### ISSUE THREAD

**Issue by keilw** [OpenDDRmobi/openddr-java#2]
OpenDDR Classifier Console null
Exception in thread "main" java.lang.NullPointerException: URL Path cannot be null
	at mobi.openddr.classifier.loader.impl.URLResource.<init>(URLResource.java:34)
	at mobi.openddr.classifier.loader.LoaderFactory.getLoader(LoaderFactory.java:41)
	at mobi.openddr.classifier.Classifier.initDeviceData(Classifier.java:65)
	at mobi.openddr.classifier.console.ClassifierConsole.main(ClassifierConsole.java:162)

**Comment by keilw** [comment]
Fixed. passing no path will result in error message and mention of help on necessary options.
